# =============================================
# KOTOBALEARN - Configuration principale
# =============================================

# Base de données PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/kotobalearn
spring.datasource.username=postgres
spring.profiles.include=secret
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
# validate = Hibernate vérifie les entités sans toucher aux tables (Flyway s'en charge)
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Désactive l'anti-pattern open-in-view
spring.jpa.open-in-view=false

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Nom et port
spring.application.name=kotobalearn-backend
server.port=8080